version: "3"
services:
  node_peliculas:
    build: .
#    command: npm start
    restart: always
    environment:
      PORT_PELICULAS: 3000
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "4000:3000"
