version: "3"
services:
  node_peliculas:
    build: .
#    command: npm start
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    expose:
      - "3000"
    ports:
      - "4000:3000"
